
'abraham marte'
'abu dhabi'
'abu dhabi etc.'
'abu dhabi pro'
'abu dhabi world pro'
'abudhabi'
' copy podio'
'pro fight to win  copa podio submission series pro defunct  defunct'
'aesopian'
'afbjj'
'aikido sangenkai'
'aj agazarm instructors friend'
'aleksander karelin'
'alexandre riberio'
' demian maia.'
' ebi'
' fight to win'
' gary tonon'
' gordon ryan'
' have ed  in the past.'
' i can go on.'
' i  to joe '
' im happy to support them. fuck ralek.'
' lucas lepri'
' replays of jiu jitsu matches.'
' ryan hall'
' streams of .'
' the stuff that shows up on  .'
' to see cool techniques'
' while it isnt pure jiu jitsu'
' will probably pay to see the upcomming ebi. i will never pay for .'
'andr galvao'
'andre galvao'
'andre galvao. rodolfo viera'
'andre galvao. rubens charles'
'andre galvo'
'angelica galvao'
'antonio rodrigo nogueira'
'anybody whos sexy plays a fun game.'
'aoki'
'arrrrr slash bjj'
'art of jiu jitsu'
'artichoke media'
'as above'
'as i have read that multiple athletes have complained of non payment. moreover'
'australian jiu jitsu gr prix'
'awkward shaka'
'basically just /r/bjj'
'because of the timezones i download them. i  ebi'
'beerkut depending on the card.'
'berkut'
'berkut... i  it via '
'bernardio faria'
'bernardo faria'
'bernardo faria  gui mendes'
'bernardo faria rodolfo vieira marcelo garcia'
'big fan of '
'big gi  tend to be largely boring  too much to . better to see the highlight reel later.'
'big jiu jitsu'
'bill cooper'
'bjee.com jui jitsutimes.com bjj.com'
'bjj collective'
'shersog forum'
'bjj globetrotter'
'bjj hacks'
'bjj heroes'
'bjj heros'
'bjj insider'
'bjj library'
'bjj library  '
'bjj news'
'bjj news.'
'bjj on  '

'bjj over 40  '
'bjj problems'
'bjj '
' '
' tristar'
' chewjitsu  budo videos  bjj breakdown  grapple arts'
'bjj style'
'bjjcanvas'
'bjjcollective'
'bjjcollective.com'
'bjjcollectve'
'bjje'
' bjj heroes jiujitsu times bjj after 40'
'  jiu jitsu times jiu jitsu style'
' stephan kestings emails sherdog grappling forum'
'.com mixedmartialarts.com'
'.com. jujitsutimes.com. '
'bjjhacks'
'bjjheroes'
'bjjhq.com grapplearts.com'
'bjjjoe'
'bjjnees.com'
'bjjweekly.com'
'bleacher report'
'bloody elbow'
'bloody elbow //  for interviews  technique'
'bloody elbow. cagepotato be great. they all host some grappling content.'
'bloodyelbow'
'bloodyelbow  submission radio'
'bloodyelbow.com'
'bloodyelbow.com mma'
'boa super 8'
'brags neto'
'brandon mullins'
'braulio'
'braulio estima'
'bravo'
'brazilian jiu jitsu  '
'breaking muscle'
'breaking muscle several of their bloggers train bjj'
'breakingmuscle'
'brian ortega'
'brick'
'bro away the gi'
'bro away the gi open mat radio'
'bruno malfacine'
'bruno malfacine andre galvao'
'bruno malfacine.'
'buchecha'
'buchecha.'
'budo jake'
'budo video'
'budojake vids'
'budovideos'
'bushecha'
'but a lot of mma stuff. underground'
'but co main event podcast is excellent.'
'but collective'
'but could be wrong.'
'but got too busy'
'but i cant get how you can just talk about grappling. theres no video to comment on'
'but i do enjoy rener gracies  channel  i  to the joe  experience from time to time'
'but i enjoy joe  podcast.'
'but i love bjj girl  blogs centered around womens bjj.'
'but mostly in person at .'
'but not digging . i  on ufc fight pass'
'but not so much anymore.'
'but thats because i dont want to commit full days to ing a tournament at the other side of the world'
'but   catch matches on  later.'
'but   after the events'
'but will also  ufc paying special attention to implementations of jiu jitsu with a striking opponent.'
'but you can find good info.'
'cage side concussion cast'
'cageside concussion'
'cageside concussion cast'
'cageside concussion cast previously followed insidebjj'
'cageside concussioncast'
'cageside concussions cast'
'caio terra'
'chael p sonnen'
'chael sonnen'
'cheap seats with jordan breen  greg savage'
'chris haueter'
'christian graugart'
'ciao tera'
'ciao terra'
'clark gracie'
'claudinha gadelha'
'comprido'
'concussion cast'
'copa podia'
'copa podia etc etc.'
'copa podio'
'copa podio  every other event that features good fights.  if i can find friends to share the costs'
'cornelius'
'cummings'
'cyborg'
'cyborg abreu'
'd. maia'
'damian maia'
'damian maia&gary tonon are killing it right now'
'damian miai'
'damien maia'
'danaher'
'danaher death squad'
'danahers group'
'daniel beleza'
'daniel beleza guybson sa'
'daniel strauss the raspberry ape'
'dave camarillo'
'dave camarillo podcast'
'davi ramos'
'dds'
'dean lister'
'dean lister  eddie cummings'
'demian maia'
'demian maia ufc ... so mmonsters out there'
'demian maya'
'dern'
'dillon danis'
'dirty white belr'
'dirty white belt'
'does jre count'
'does  count'
'does the joe  experience count motus v with nick the tooth'
'dominyka obelenyte'
'dominyka obelenyte.'
'dont have time  prefer mma fights.'
'dont pay for  but  free replays of   i come across organically'
'dont really keep up with it. just  old  videos.'
'dont really  to any.'
'dragon ball z'
'dstryr'
'dvds   vids'
'early matt serra'
'6 absolute'
'abu dhabi '
' metaoirs'
'meta  copa'
'  copa podia'
'mostly  the random match on the internet. i also attended worlds 2015 as a spectator.'
'ufc fight pass  not sure where i ed it last'
' replays on ufc fight pass'
' worlds adcv.   on .  you tube'
'ebis'
'edi  worlds'
'eduardo telles'
'edwin najmi'
'elevate mma blog'
'emily kwok'
'erberth santos'
'eric paulson'
'europeans  copa podio'
'even though he doesnt talk much about grappling.'
'even though its not bjj specific anytime joe  has a bjj guest its fun to  too.'
'every mayor bjj company'
'everything available at   copa podio'
'excited for sonnens new organization'
'f12'
'fabricio werdum'
'feeds such as john danaher'
'fan of james fosters 300 podcast.'
'faria'
'felicia oh'
'felipe pena'
'felipe pena  mmore..'
'fighter  the kid'
'fighter  the kid both vaguely related'
'fightland'
'fightl grapplingarts elevate mma blogs'
'finisher'
'finishers'
'finishers podcast'
'finishers.'
'five element grappling'
'formiga barbosa'
'foster 300'
'fp independent.'
'free broadcasts from worlds'
'free streams like bjjtour'
'gabi garcia'
'gabriel arges'
'galva0'
'galvao'
'galvao.'
'gambledub  tristar gym on .'
'garry'
'garry tonan'
'garry tonin'
'garry tonnen'
'garry tonnon'
'garry tonon'
'garry tonon / marcelo garcia / eduardo telles / kazushi sakuraba / enson inoue'
'garry tonon.'
'gary tonan'
'gary tonnon'
'gary tonon'
'gary tonon  ryan hall'
'gary tonon.'
'genki sudo'
'geo martinez'
'geo martinez  jeff glover'
'geo martinez renzo gracie'
'georgettes jiu jitsu blog'
'gezary'
'gezary matuda'
'gi reviews.net'
'gianni grippo'
'gingersnaps.me.'
'glover'
'goodfight . i  on '
'gordan ryan'
'gordon ryan'
'gordon ryan.'
'gracia'
'gracie breakdown vids'
'gracie breakdowns not really a blog website'
'gracie jiu jitsu rocks'
'gracie jiujitsu rocks'
'gracie magazine'
'graciemag'
'gracieuniversity  awkward shaka'
'gracieuniversity.com'
'grapple arts'
'grapplearts'
'grapplearts app'
'grapplearts podcast'
'grapplearts radio'
'grapplearts radio is only grapling specific podcast. joe   jocko podcasts are sort of related.'
'grapplearts radio. wogjitsu radio'
'grapplearts  bjj bjj eu jj times'
'grapplearts.com'
'grapplearts.com.'
'grappleing podcast'
'grapplerinfo'
'grapplers guide'
'grapplersguide.com'
'grappling center'
'grappling industries'
'grappling podcast'
'grappplersparadiese.com'
'gray tonnin'
'great grappling'
'grippo'
'grumpy grappler'
'grumpy grappler dirty white belt'
'gsp'
'gui  rafa mendes'
'gui mendes'
'guilherme mendes'
'gunnar nelson'
'guybson sa  jake shields'
'gym crew gets together to .'
'hannette staack'
'havent found one that doesnt seem like a circle jerks.'
'heavy hands'
'helio soneca'
'helvecio penna'
'hickson  kron'
'hiddenjiujitsu.com'
'i always like monson  barnett. now i like tonnen'
'i do quite like kron gracie because hes beautiful....'
'i dont underst podcasts. maybe i havent found the right one'
'i dont  particular organizations. i now avoid  out of principle'
'i find most matches after the fact on . '
'i follow buchecha'
'i go to  for inspiration'
'i have a  membership   all the stuff they stream  mostly  but some others as well'
'i have a  subscription   it all '
'i have ed  but there was a scam with payment  i will not support that organization. i wont buy ufc passes either.'
'i honestly only  matches after their put on places like  for free'
'i like blogs by women jiujius blog  georgettes . i do also read a lot of blogs written by lower belts as i can relate to these easier  i also like the bjj forum.'
'i like both highlights from big competitions'
'i like  '
'i like grapplearts&artechoke media.'
'i like to  leandro lo. his style is cool. also marcello garcia'
'i love going to  worlds '
'i love ing sport jiu jitsu'
'i never pay for s. i ed the first few  events'
'i only occasionally ...   catch highlights on  such'
'i only  a small amount of sport bjj  it is   ebi'
'i only  bjj in  never ed it . i    highlights  best bits to see if theres   i can use for my rolling.'
'i sometimes  budo jakes shows.'
'i still things off the internet.'
'i think the danaher guys cummings'
'i try to support uk events but i also    occasionally'
'i try to  as mevents as possible like '
'i   do free streams stream it with purchase with training partners'
'i  almost everything that appears on flow grappling. my current favorites are the uae events because i enjoy gi jiu jitsu  i support that they pay atheletes in tournement bjj. of course i   but i do like them as an organization. my favorite paperview is copapodio  a close second is ebi.'
'i    thats been hyped up'
'i  at home at my coaches home. we  all major events plus   else that pops up on flo'
'i  ebi'
'i    until it went all weirdo  stopped paying people. normally we  at someones house.'
'i  every kind of bjj fights i can get on the internet .  mundials  copa podium etc'
'i  highlights  sometimes match coverage but i generally dont find grappling compelling as a spectator sport.'
'i  highlights when posted on social media.'
'i     regularly. i did   but now boycott it for various reasons. i have ed one ebi.'
'i  notable matches that are shared via social media  those of my favorite jiu jitsu athletes.'
'i  ufc fights for the bjj component mixed with other arts.'
'i ed worlds on '
'i will catch a .'
'i wont pay flo a monthly fee. i like to  what i can of the major  '
'i work  compete at a lot of local competitions as part of a touring team. i have attended several submission only shows including tuff invitational'
'i wouldnt say theyre favourites but more of a deep appreciation.'
' highlights only the matches that have been recommended to me as i find some  matches can be quite tedious/boring'
'igor silva/damaian maia'
'ill  relevant matches'
'inside bjj'
'insidebjj w/ fatmatt freeman '
'inverted gears blog'
'isaac doerderlein sp'
'j.j. machado'
'jacar'
'jacare'
'jacare souza'
'jack mcvicker'
'jake shields'
'james puopolo'
'jason scully'
'jean jacques machado'
'jean jacques machado.'
'jeff clover'
'jeff glover'
'jeff glover gary tonon'
'jeff monson'
'jeff shaw'
'jits  my own aroundtheju.weebly.com'
'jiu jitology'
'jiu jitsu after dark'
'jiu jitsu daily'
'jiu jitsu forums'
'jiu jitsu portugal'
'jiu jitsu style'
'jiu jitsui times. others i cant think of. more related to the current articles.'
'jiujitsu 24/7 with lea young'
'jiujitsu after dark'
'jiujitsu after sark'
'jiujitsuempire.com'
'jiujitsuforums  .'
'jiujitsuforums.com'
'jiujitsumag'
'jiujitsuology'
'jj times'
'joao miyao'
'jocko podcast'
'jocko podcast always talks jiu jitsu'
'jocko podcast joe '
'jocko willink'
'john jones'
'jon satava'
'josh barnet'
'josh barnett'
'josh hinger'
'jre'
'jre is slightly jiu jitsu related. most others ive tried have poor audio quality that makes it difficult to  to interviews. this week in bjj from budo is good too.'
'jt torres'
'jujitsu times bjj news gracie mag'
'jujitsutimes'
'just black belt matches.'
'just joe  experience'
'kazushi sakuraba'
'keenan clark estimas xandre gerry tonnon'
'keenan. ryan hall. marcelo garcia'
'kennedy maciel'
'keon gracie'
'kim rice. i mostly see reposted articles on   from various sources.'
'kit dale'
'kneebar king of leglocks'
'kobe bryant'
'kron'
'kron gracie bjj'
'kron gracie marcelo garcia eddie cummings rafael mendes garry tonon'
'kron gracie rodolfo viera luiz heredia'
'kron gracie.'
'kron.'
'lachlan giles.'
'leandro lo'
'leandro lo for passing'
'lebron james'
'legally'
'leite'
'leo noguiera'
'leo vieira'
'leo vieira  jacare souza.'
'leo viera'
'leo/ricardo/leandro vieira.'
'leonardo neves my coach'
'leozinho'
'leticia ribeiro'
'liera jr'
'like the worlds. i also like s '
'lister'
'streams/vods'
'the match jean machado gile huni  experience'
'lots of blogs jeff shaw'
'lots of  after the competitions.'
'lots of  channels'
'lots to see on  . basically   that shows up in my feed.'
'lovato'
'lovato jr'
'loved lockflow.com now defunct'
'loz'
'lucas leite'
'lucas lepri'
'luiza monteiro'
'm xss w'
'maia'
'mainly i have fight pass9'
'mainly no gi'
'mainly submission only'
'mainly bjj.com&'
'major    comps'
'major  '
'major  .'
'makinzie dern'
'malfacine'
'malfisino'
'mama.tv sherdog'
'mansher khera'
'molder matches often refered to as classics'
'marcelo'
'marcelo  buchecha'
'marcelo mattos'
'marcio andre'
'marcio cruz'
'marcos tinoco'
'marcus almeida'
'marcus buchecha abreu'
'marcus buchecha almeida  leandro lo'
'mark hunt'
'masakazu iminari'
'matamoris'
'matheus diniz'
'matuda'
'meerkatsu scramblog william wayl powering through'
'megaton'
'megaton dias'
'riebero brothers.'
'menes'
'meta'
'mg'
'mg in action  grapplers guide bjj '
'mg in action.  jujitsu times underground'
'mga'
'mginaction'
'mginaction '
'miayo bros'
'michael langhi'
'michele nicolini'
'michelle nicolini'
'michelle nicollini'
'milton vieira'
'misc videos on '
'leandro lo.'
'miyaos'
'mma junkie'
'mma uderground'
'mma&beyond'
'mma.tv'
'mma.tvs bjj forum is my only routine bjj related site'
'mmafighting'
'mmalinker'
'mmarocks'
'monday morning analyst with luke thomas'
'montreal bjj scene'
'more recently ryan are all interesting stylistically.'
'mostly just highlights  such on '
'mostly just stuff i find is shared on . ive been meaning to  s  such but havent found out exactly what to /how to  it.'
'mostly just  videos'
'mostly   copa p dio'
'mostly  to be honest   is my favorite'
'motus v'
'motus v with nick the tooth'
'mr. miyagi'
'mundials'
'murillo b'
'murilo santana'
'my gym often has set up a screen  people will come over to  ebi'
'my teammates'
'my training partners'
'naga'
'naga  grapplers quest all on . other matches that i can find on  as well'
'narato laranja'
'nate diaz'
'nathan orchard'
'nicholas meregali'
'nick the tooth'
'nicolini'
'nino schembri'
'no holds barred radio with eddie goldman'
'no technique to demonstrate etc. if i want news updates'
'nogueira both'
'oli'
'only  the  cards'
'only  attending us grappling events'
'onnit invitational'
'open mat radio'
'or other event i can find . i use  flow grappling typically  occasionally .'
'osiander'
'ottavia bourdain'
'pan ams'
'pan pacs.'
'panams'
'pans'
'pans etc'
'pasando guardia'
'pasandoguardia.com flowgrappling.com .com bjjheroes.com '
'paulo  joao miyao'
'paulo miyao'
'pedro sauer'
'position impossible'
'powerful jre covers mtopics including grappling'
's &ebi.  older competition footage.'
'previously ed '
'rafa'
'rafa  gui mendes'
'rafa mendes'
'rafael mendes'
'rafael mendez'
'raffael mendes'
'rafi'
'ralph'
'random highlights'
'random matches on '
'rarely   just you tube forum clips of interesting matches'
'raspberry ape'
'raspberry ape podcast grapplearts podcast this week in bjj'
'really   i can .'
'really none for grappling specific'
'rener gracie'
'reno ryan gordo nino'
'renzo'
'rhadi ferguson'
'ribeiro bros'
'ribeiro bros.'
'ribeiro brothers. lovato. tonon. marcelo.'
'riberio brothers'
'ribero brothers  ryan hall all because of their high quality instructional materials'
'ricardo vieira'
'richie martinez'
'robert cyborg abreu'
'robert drysdale'
'robert drysdale my master'
'robert drysdale only because i trained in vegas with him for over a year. hes the man.'
'roberto saitoshi'
'roberto satoshi'
'robin'
'robson moura'
'roger'
'roger gracie michelle nicollini gary tonon'
'roger gracie.'
'roger is amazing keeps it classic. i d in la for 3 years  trained with ryron gracie. the knowledge is outrageous. best personality ever. i may be 200 pounds but i try to act  play like jeff glover  the reason i got into the sport is bj penn  the california kid urijah faber'
'rolando samson'
'rolando samson  leandro lo'
'rolled up'
'rollmore.com bjjhq.com'
'romalo barral'
'romulo'
'romulo barral'
'romulo barral  buchecha'
'ronaldo jacare'
'ronaldo souza'
'ronda rousey'
'rousimar palhares'
'roy marsh'
'royler'
'ryan hall'
'ryron gracie'
'sakuraba'
'scrambel blog'
'scramblestuff bjjheroes'
'seldom  inked except on highlight reels'
'sheepdog'
'sheepdog f12'
'shinya aoki'
'show the art'
'show the art podcast'
'showtheart'
'skirt on the mat'
'slideyfoot'
'small doses of eddie bravo'
'soluco'
'specifically jason scully  firas zahabi channels'
'streams'
'stuart cooper'
'stuff on  '
'stuff on  occasionally'
'sub only comps'
'subbed'
'submission only events.'
'submission101'
'sweep'
't.v'
'take it uneasy'
'tammi musumeci michelle nicolini'
'tanquinho mendes'
'tatame'
'telles'
'terere'
'that one that gets posted on the  sometimes that got annoyed with  for saying faggot is   pretty good.'
'the  feed'
'the art of jiujitsu  membership'
'the bjj  that brought me here.'
'the budo bum'
'the cageside concussioncast open mat radio'
'the danaher death squad'
'the eddie bravo podcast when he does it .'
'the fighter  the kid'
'the finishers podcast'
'the grappling central podcast'
'the grumpy grappler aesopian arthechoke media wrestlejitsu'
'the jiu jitsu podcast'
'the joe  experience'
'the miyao bros'
'the miyao brothers'
'the miyaos'
'the ones that show technices executed by shorter people simple technical moves'
'the philosograppler dave camarillo'
'the product quality has suffered.'
'the ribeiro brothers'
'the subbed'
'the ug'
'the worlds'
'themmacommunity'
'then just exploring from there.'
'then matches of athletes like miyao brothers'
'there are a lot marcelo garcias style fascinates me. i love ing buchecha fight. garry tonon is exciting. ive recently become a fan of yuri simoes.  there are more.'
'there are a lot of   pages that share posts. i do really enjoy show the art.'
'there arent a lot that are that interesting unfortunately. i like   read articles that get posted there.'
'they are very uneven so i suppose i enjoy jre more than everything else even if i often disagree with him'
'this american life'
'this week in bjj'
'those documentaries like jiu jitsu in socal'
'those of gym members'
'tim kennedy'
'to name just a few'
'to  percy harvin to have a beer with almost anyone other than percy harvin'
'tom brady'
'tonan'
'tonner'
'tonnon'
'tonon'
'tonon/ gordon ryan'
'too mto list.'
'torrents'
' on brazilian cable tv.'
'train by day'
'travis stevens'
'try to   when i can'
'trystar gym  channel bjjscout  channel joe  podcast'
'tuff invitational'
'twibjj'
'uaejff'
'uaejj'
'ufc'
'ug grappling sub forum'
'underground'
'us grappling'
'valerie worthington'
'vanderson gomez'
'verbal tap'
'verbal tapcast'
'very rarely '
'via  stream .'
'via the internet.'
'victor'
'viera'
'vinny magalhaes'
'wbbjj.com'
'werdum'
'werdum.'
'wolverine mullins'
'xande'
'xande ribiero'
'xande roger saulo micheal leria kron michelle nicollne caio erra'
'xande/saulo ribeiro'
'xhamster.com'
'yeah  i  all except cause that stuff gets kinda lame. i like the kron gracie match rodolfo viera  so on people who do good jiu jitsu'
'yoga for bjj'
'your blog is very nice'
'zahabi tristar gym'
'zegrapplez'