'24 hour fitness'
'302 bjj'
'5th dimension drysdale zenith'
'a judo club'
'a royce gracie affiliate'
'a team sas affiliate'
'absolute mma maromba academia international'
'absoluto eddie kone'
'academia john baylon clube de jiu jitsu filipinas'
'accademia kama'
'acemat ribeiro jiu jitsu'
'aforce bjj andre montinero'
'agoge combatives rigan machado affiliate'
'ahjo training center de la riva finland affiliate'
'alamance black belt academy team roc'
'alchemy combat club dark horse bjj'
'alexey cruz bjj new england united'
'ali dinar jiu jitsu de la riva'

'aloha academy jiu jitsu'
'also train no gi at lavin mma'
'alvarez bjj bruno bastos association'
'american martial arts academy a lucas lepri affiliate'
'anibal lobo academy rcw team pedro sauer'
'aranha nova u iao'
'arena dortmund'
'ares bjj'
'arte suave checkmat'
'as those cunts recently switched affiliation to tli i am leaving soon'
'ascension'
'asjk aalborg yogui bjj'
'asjk yogui bjj affiliate'
'atlanta ga'
'atos brisbane mota vation jiu jitsu atos affiliate'
'att'
'att valdosta'
'az'
'b19 paris de la riva'
'balance studios relson gracie affiliate'
'ballards academy of brazilian jiu jitsu and mixed martial arts'
'barbosa jj'
'basketak'
'bay jiu jitsu checkmat'
'beckley bjj sas affiliate'
'behring'
'beleza bjj sas team usa'
'beleza jiu jitsu sas team usa'
'bjj lab caio terra associate'
'bjj orl ans'
'bjjaa checkmat'
'black house team nogueria'
'bodyflo sheffield gracie barra affiliate'
'boise base alliance affilate'
'boston bjj gracie barra'
'boxing works sydney nova uniao'
'brad sandoval'
'brasa'
'brazil 021'
'brazil021'
'brazilian jiu jitsu team malta a rogerio olegairo affiliate'
'brooklynbjj'
'bruno bastos'
'brunswick bjj'
'btt'
'btt jax'
'budo academy tukaha bjj'
'but well leave soon because this is rather a fitness studio and will offer no more bjj'
'caique jiu jitsu'
'carlos farias bjj'

'carlsons'
'cassio werneck bjj'
'cavalo bjj canada cavalo bjj'
'cerberus bjj'
'champions creed martial arts a roy harris affiliate'
'champions creed martial arts roy harris affiliate'
'charlottesville bjj bjj revolution team this is former affiliation i recently moved and cannot train at this time'
'charlottesville bjj revolution bjj'
'checkmat'
'checkmat bjj'
'checkmat romania'
'choice martial arts cody houston'
'chris atkins jiu jitsu'
'chris rees academy'
'chu to bu brasa affiliate'
'city thong flowing arts'
'clare brazilian jiu jitsu academy'
'cobrinha alliance los angeles'
'coelh o jiu jitsu germany'
'colombian federation of jiu jitsu&nino schembri one or two months a year'
'combat fitness sbg'
'combat jiu jitsu academy'
'combat sports academy a gracie fighter affiliate'
'combative sports center daniel de lima affiliate'
'connection gracie jiu jitsu nil affiliation'
'conquest bjj vicente jr team'
'copacabana team'
'corvos combat'
'crazy monkey defense'
'crispim bjj'
'crucifix grappling rio grappling club'
'cville bjj revolution bjj'
'daniel beleza bjj sas team'
'daniel beleza brazilian jiu jitsu'
'darkside'
'dc bjj yamasaki affiliate'
'ddr bjj'
'ddr chico ddr'
'de la riva'
'de la riva dublin and infini jiu jitsu strabourg bjj globetrotters'
'dedeco bjj'
'defkon 1 roberto traven'
'deftac cebu a ribeiro jiu jitsu affiliate'
'deftac philippines ribeiro jiujitsu affiliate'
'diaz martial arts'
'dojo kyle cleber luciano affiliate'
'drill bjj'
'drive mma'
'drysdale bjj zenith'
'east coast united bjj'
'easton bjj a renzo gracie affiliate'
'edmonds bjj gracie barra affiliate'
'ekbjj'
'element bjj marcelo garcia'
'element bjj vt1 affiliate'
'elements academy of martial arts a riyce gracie affiliate'
'elevate mma'
'elevate mma academy zenith bjj'
'elevate mma zenith bjj affiliate'
'empire jiu jitsu unaffiliated white black under relson gracie'
'enso jiu jitsu oregon city'
'equipe master wilson australia'
'escola de lutas niter i luiz paulo jiu jitsu affiliate'
'evolution grappling academy a soul fighters affiliate'
'evolution training guerilla jiu jitsu affiliate'
'evolution training guerrilla jiu jitsu'
'fabio santos'
'factory x'
'fenix bjj'
'ferrari bjj'
'fight to win bjj'
'fight to win bjj denver nc royce gracie affiliate'
'fight to win team steve hall a royce gracie affiliate'
'filipe barbosa bjj academy'
'fit factory bjj samuel braga affiliate'
'flow martial arts'
'forged fitness'
'forged fitness royce affiliate'
'forged fitness royce gracie'
'fort mill'
'fortitude brazilian jiu jitsu game fight bjj'
'fox valley grappling club'
'frontline academy'
'frontline academy oslo'
'frontline muay thai a roger gracie affiliate'
'fullhouse'
'g vle ju jutsu dynamix fighting sports'
'gas porto agas jiu jitsu affiliate'
'germanos team carlson gracie'
'gft affiliate'
'gi at north bay jiu jitsu eduardo rocha affiliate under ribeiro jj'
'global martial art gracie humaita'
'glory mma&fitness leonardo pecanha nova uniao'

'gracie combatives'
'gracie humait israel'
'gracie humaita in southeast missouri'
'gracie humaita robin gracie'
'gracie humatia'
'gracie jiu jitsu cape town'
'gracie palm harbor a gracie tampa affiliate'
'gracie raleigh a royce gracie affiliate'
'gracie tampa'
'gracie technics pedro sauer affiliate'
'gracie winnipeg'
'grapplers69 icon jiu jitsu team'
'grappling fight team gft'
'great grappling bjj'
'great grappling bjj gordo jiu jitsu affiliate'
'greubels mma an alliance affiliate'
'ground pressure team rogerio olegario affiliate'
'ground zero bjj'
'gsw john will rigan machado affiliate'
'guerilla jiu jitsu'
'guerrilla dave camarillo'
'gunnison jiu jitsu a gracie academy affiliate'
'gustavo machado'
'gustavo machado bjj rocky mount'
'guy mezgers combat sports club checkmat'
'helios bjj ribeiro affiliate'
'hilti bjj stockholm hilti bjj'
'hipko checkmate'
'hollywood bjj a paragon affiliate'
'huntington wv'
'hurricane jiu jitsu'
'hvmac machado'
'icon'
'icon bjj ede'
'icon lyon icon bjj affiliate'
'im an independant teacher practitioner'
'impact jiu jitsu'
'impact mma checkmat affiliate'
'infinite fighting concepts atos'
'infinity bjj bjj revolution'
'infinity brazilian jiu jitsu'
'international aikikai federation'
'ironside martial arts'
'ironside mma'
'its not affiliated'
'jaguar bjj'
'jean jaques machado affiliate'
'jiu jitsu kingdom'
'jiu jitsu league atos'
'john frankl'
'johns gym an independent in central texas'
'jr academy formerly under bracie barra'
'juggernaut fight club'
'jungle bjj'
'juniko'
'kaboom bjj rafael lavato jr affiliate'
'kazgan mma'
'kcbjj renato tavares'
'kenny kim bjj caio terra association'
'kimura bjj serbia'
'kimura nova uniao'
'kimura serbia'
'kioto bjj port jefferson'
'kl ber jiu jitsu nova uni o'
'koa fitness'
'korea jiu jitsu academy rickson gracie affiliate'
'kristiansand kampsport senter yogui bjj affiliate'
'kyoto nyc'
'lansing bjj'
'legion 13 peter de been affiliate'
'lin martial arts'
'lobo jiu jitsu academy pedro sauer affiliate'
'london fight factory checkmat'
'los alamos brazillian jiu jitsu gracie barra'
'loughborough bjj'
'luiz claudio rickson gracie'
'lund grappling academy dynamix'
'm1j14 bjj'
'm3 fight and fitness gfteam usa'
'mabjj carlson gracie international'
'mac tirol'
'mac tirol a budo clan affiliate'
'mac tirol budo clan'
'macarra bjj marcio stambowski'
'maidenhead martial arts'
'marcelo alonso'
'marcelo garcia'
'marcelo garcia academy alliance'
'marshmallow bjj csw nova uniao'
'martial arts academy of southern pines royce gracie affiliate'
'maryland judo and jiu jitsu academy relson gracie affiliate'
'mat chess mma'
'mckenzie bjj checkmat'
'mcvicker bjj'
'md royce gracie affiliate'
'medavia bjj carslon gracie team gilbert'
'memphis bjj marcelo garcia affiliate'
'memphis judo and jiu jitsu'
'milanimal'
'millers martial arts'
'milton bastos'
'minnesota martial arts academy pedro sauer'
'mj lnir sbgi'
'mma and sport pedro sauer affiliate'
'mma rovaniemi'
'modesto power cleber luciano affiliate'
'montanha jiu jitsu'
'montreal bjj revolution'
'ms jiu jitsu alliance bd affiliate'
'muzio bjj gavea gym brasa'
'mybjj team'
'na'
'neves brazilian jiujitsu association independent'
'new breed chicago bonsai'
'new breed training center bonsai jj'
'next level combat gf team 10th planet jiu jitsu'
'nexus'
'ngma vsbjj affiliate'
'no affilation'
'no affiliation'
'no longer a member'
'noel smith bjj a renato tavares affiliate'
'none'
'none were not affiliated'
'north georgia'
'north van bjj'
'norway'
'not affiliated'
'not affiliated indepedent academy in sydney'
'nova forca uk'
'nova gyms'
'nova vida'
'nu'
'nvbjj gracie academyu'
'oc carlson gracie orange'
'oceanside bjj a royce gracie affiliate'
'octagon mma'
'oksa non affiliated'
'olsons martial arts a aped to sauer affiliate'
'openmat bjj shawn williams affiliate'
'ottawa academy of martial arts a renzo gracie affiliate'
'overwhelm mma'
'pa combat sports 2016 current'
'pacific integrated martial arts and anibal lobo jiu jitsu gracie jiu jitsu'
'pacific ring sports a fabio prado affiliate'
'panda dojo globetrotters'
'paragon'
'pat robinsons choke u'
'peak bjj'
'pedro sauer affiliate'
'pendergrass academy a gustavo machado affiliate'
'peoria athletic club jack mcvicker'
'performance martial arts academy a ribeiro lovato affiliate'
'peter debeen affiliate'
'pitch black mma rcj machado bjj'
'plus one defense'
'portugal gold team team juncao affiliate'
'poseidon bjj&berserk mma'
'pound for pound'
'ppmac pedro sauer'
'prime bjj'
'prime brazilian jiu jitsu'
'prince rupert bjj'
'psbjj'
'ralph gracie'
'ralph gracie bend'
'ralph gracie jj'
'raptor bjj'
'rather not say'
'real world martial arts renzo gracie affiliate'
'rebellion academy checkmat affiliate'
'redline fight sports carlos neto bjj'
'relson'
'relson gracie'
'renato tavares association'
'renato taveres bjj'
'renegade mma affiliate of australian elite team'
'revolution bjj bjj revolution'
'revolution bjj carlson gracie'
'ribeiro bjj'
'ribeiro jiu jitsu manaus'
'ribeiro jiu jitsu vancouver saulo&xande ribeiro'
'rice bros bjj'
'richmond bjj revolution bjj'
'rilion gracie gracie elite team'
'rio grappling club bih'
'rio pro bjj'
'riptide bjj riberio affiliate'
'river city warriors a pedro sauer affiliate'
'river city warriors anibal lobo jiu jitsu pedro sauer affliate'
'river city warriors pedro sauer'
'rjc machado'
'rob stevens bjj'
'robert drysdale bjj affiliate'

'rohan machado'
'romulo melo bjj academy'
'roots bjj'
'rose city warriors lobo jiu jitsu a pedro sauer affiliate'
'round won jiu jitsu'
'roy harris'

'royler gracie jiu jitsu'
'roys magical shed'
'rubao carioca section 8 mma'
'sampa jiujitsu quebec'
'sankuno no affiliation'
'saparito jiu jitsu tallahassee'
'sas team syracuse a sas team affiliate'
'sas team usa beleza'
'sbg'
'sc gordo'
'seattle integrated martial arts a northwest jiu jitsu academy affilate'
'serao academy no affiliation'
'serg bjj marcio cruz affiliate'
'sharktank bjj kuwait'
'siege mma one jiu jitsu'
'silver fox bjj renzo gracie affiliate'
'sion bjj'
'six levels mma and fitness a royce gracie affiliate'
'sjbjj ricardo almedia association'
'soca bjj'
'soul fighters'
'soulcraft bjj a macarra bjj marcio stambowsky affiliate'
'southern cross jiu jitsu academy nova uniao'
'spartacus bjj usa'
'stafford bjj big brothers leo dalla affiliate'
'start academy a renzo gracie affiliate'
'steve hall royce gracie'
'straight blast gym toronto'
'studio 540'
'tai kai jiu jitsu team balance'
'tama martial arts'
'tatoru kumamoto once affiliated with paraestra but no longer'
'team balance baltimore bjj gamma'
'team beauregard bjj revolution'
'team brasa compreido'
'team de jager the hague'
'team link'
'team pedro sauer affiliate'
'team predador'
'team redaovic'
'team roc charlotte royce gracie affiliate'
'team shark bjj daniel pinheiro'
'team torres alexander charutto'
'the base training centet'
'the jiu jitsu club flagstaff'
'the lab team big brothers'
'the netherlands'
'tiger martial arts academy pedro sauer affiliate'
'tiger shark bjj'
'tipping point bjj bonsai jj'
'tjj'
'tjj durham'
'tjj royce affiliate'
'tjj royce gracie'
'tom deblass ocbjj'
'toplevel martial arts pedro sauler affiliate'
'toronto bjj ribiero brothers affiliate'
'training grounds nj'
'triad martial art a rickson gracie carlos machado affiliate'
'triangle jiu jitsu a royce gracie affiliate'
'triangle jiu jitsu academy team royce gracie affiliate'
'triangle jiu jitsu durham a royce gracie affiliate'
'triangle jiu jitsu durham royce gracie'
'triangle jiu jitsu durham royce gracie affiliate'
'triangle jiu jitsu royce gracie'
'triangle jiujitsu royce gracie'
'triangle jj durham nc'
'triangle jui jitsu team royce gracie'
'trident mma rigan machado affiliate'
'tristar gym'
'triton fight center rentao tavares carlson gracie'
'triumph bjj gf team'
'triune bjj ares bjj'
'true believer jiu jitsu'
'tx'
'ucla recreation martial arts'
'uk'
'uks budo'
'universal bjj zenith drysdale affilate'
'universal combat academy john will machado'
'universal mma zenith bjj'
'university of jiu jitsu'
'university of jiu jitsu ribeiro association'
'urbana academy pedro sauer affiliate'
'vagner boca bjj'
'valko bjj'
'vanderson gomes bjj'
'vandry jiu jitsu a macho affiliate before that anibal lobo brazilian jiu jitsu pedro sauer affiliate'
'vermont bjj'
'werdum combat team'
'west coast jiu jitsu'
'will machado'
'will machardo'
'windsor brazilian jiu jitsu a jean jacques machado affiliate'
'wolf pack royce gracie'
'workshop jiu jitsu nyc renzo gracie john danaher black belt instructor'
'xequemate luiz palhares affiliate'
'z radiola association ex gracie barra'
'zanshin dojo nashville 2006 2009'
'zenith'
'zenith bjj'
'zenquest damian maia affiliate'
'zero bjj beleza jujitsu affiliate'
'zero bjj team sas'
'zicro bjj tallahassee alliance'
'zingano bjj luiz claudio combat team'
'zr team'